spring:

  sql:
    init:
      mode: always

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/comma
    username: donggi
    password: '0408'

  jpa:
    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.MySQL8Dialect

    defer-datasource-initialization: true

    properties:
      hibernate:
        format_sql: true
        show-sql: true

