name: CI - BE

on:
  push:
    branches:
      - be
  pull_request:
    branches: [ be ]
    paths:
      [
        "src/**",
        "build.gradle",
      ]
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

jobs:
  build:
    name: SpringBoot Test
    runs-on: ubuntu-20.04
    environment:
      name: github actions setup mysql
      url: https://github.com/donggi-lee-bit/comma/settings/environments/853859783/edit
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0'
          mysql database: 'commatest'
          mysql user: 'donggi'
          mysql password: ${{ secrets.DatabasePassword }}

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Use Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Grant Execute Permission For Gradlew
        run: chmod +x gradlew

      - name: Test With Gradle
        run: ./gradlew test
